### ISSUE TITLE
plot vicon trajectories

### ISSUE THREAD

**Issue by JonnyG123789** [robotic-esp/dataset_tools#5] opened 2023-02-09 01:27 UTC
Hello,there is a question:
when i load vicon data by " ingest_vicon_data.m",and plot trajctories by " plot_multiple_trajectories.m". The results is different with your paper. Example fo dataset "swinging_translation":
![image](https://user-images.githubusercontent.com/63381812/217691119-caf589b6-706f-4cff-afd1-9c4daed3411a.png)
This is the trajtory provided in your paper.
&&&&

This is plot by the code:
![untitled](https://user-images.githubusercontent.com/63381812/217691203-c734d8bf-0050-4d90-af04-435f0bcabe90.jpg)

Is any parameters not correct?

**Comment by gammell** [comment] 2023-02-09 03:07
Hi @JonnyG123789 ,

Thanks for your interest in using the OMD. Can you please post a minimum working example of your code to generate the figure so that we can replicate the issue.

Thanks,
Jon

**Comment by JonnyG123789** [comment] 2023-02-09 03:37
Thanks for your reply! The code used to plot trajectories is provided by the “tools”&nbsp; in OMD website. The trajectory data is vicon.csv in “swinging_translation”.



---Original---
From: "Jonathan ***@***.***&gt;
Date: Thu, Feb 9, 2023 11:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [robotic-esp/dataset_tools] plot vicon trajectories (Issue #5)




 
Hi @JonnyG123789 ,
 
Thanks for your interest in using the OMD. Can you please post a minimum working example of your code to generate the figure so that we can replicate the issue.
 
Thanks,
 Jon

**Comment by gammell** [comment] 2023-02-09 14:43
Hi @JonnyG123789, I'm sorry, but we are unable to help unless you provide a minimum working example of code that we can run and replicate the error.

**Edit**: Please also include details about which specific data segment you are using.

**Comment by JonnyG123789** [comment] 2023-02-10 02:39
OK。First,the "ingest_vicon_data.m" provided in "https://github.com/robotic-esp/dataset_tools" to load csv file, and its code is:
 
```
function [vicon_trajectories, vicon_objects, vicon_timestamps] = ingest_vicon_data(filename)
%
% Parses vicon data from input csv into trajectory and timestamp data.
%
% From: Kevin M. Judd and Jonathan D. Gammell, 
%       The Oxford Multimotion Dataset: Multiple SE(3) Motions with Ground Truth
%       kjudd@robots.ox.ac.uk, gammell@robots.ox.ac.uk
%
% input:
%   filename: input csv filename
%
% output:
%   vicon_trajectories: Mx1 cell array of the M objects tracked in the
%   vicon file, where each cell contains a Kx1 cell array of global 4x4
%   transformation matrices representing each trajectory
%   vicon_timestamps: Kx1 vector of timestamps
%

% load vicon data
vicon_data = readtable(filename);
vicon_objects = unique(vicon_data.object);
vicon_trajectories = cell(length(vicon_objects),1);

w = waitbar(0, '');
for i=1:size(vicon_data,1)
    ind = find(contains(vicon_objects, vicon_data{i,3}));
    vicon_trajectories{ind}{end+1,1} = reshape(vicon_data{i,11:end}',4,4)';
    waitbar(i/size(vicon_data,1),w, [num2str(i) '/' num2str(size(vicon_data,1)) ' entries read']);
end
close(w);
vicon_timestamps = vicon_data{1:length(vicon_trajectories):end,1} + vicon_data{1:length(vicon_trajectories):end,2}/1e9;
end
```

And then,using "plot_multiple_trajectories" to plot trajectory.The    code is:

```
function [] = plot_multiple_trajectories(trajectories, f, plotrange, stepsize)
%
% Incrementally plots the motion histories defined by trajectories.
%
% From: Kevin M. Judd and Jonathan D. Gammell, 
%       The Oxford Multimotion Dataset: Multiple SE(3) Motions with Ground Truth
%       kjudd@robots.ox.ac.uk, gammell@robots.ox.ac.uk
%
% input:
%   trajectories: Mx1 cell array of the M objects tracked in the
%   vicon file, where each cell contains a Kx1 cell array of global 4x4
%   transformation matrices representing each trajectory
%   f: figure handle on which to plot the trajectories
%   plotrange: 2x1 array defining the lower and upper index limits to plot
%   stepsize: increment between plot steps
%
% output:
%

if nargin == 1
    f = figure;
    plotrange = [1 length(trajectories{1})];
    stepsize = 1;
elseif nargin == 2
    plotrange = [1 length(trajectories{1})];
    stepsize = 1;
elseif nargin == 3
    stepsize = 1;
end

for i = 2:length(trajectories)
    if length(trajectories{i}) < plotrange(2)
        error('ERROR - mismatched trajectory lengths or plotrange limit too large')
    end
end

set(0, 'CurrentFigure', f)
hold off;
for j = 1:length(trajectories)
    plot_single_trajectory(trajectories{j}(plotrange(1):10:plotrange(2)));
    hold on
end

end
```

The  swinging_translation's csv file is used , and the results as follows:
![image](https://user-images.githubusercontent.com/63381812/217986265-af553052-c92a-47d5-a77e-6b59f7821ef0.png)
It seems like incorrect. Did I make some mistakes in running the code？Thank you for your reply,again!

**Comment by gammell** [comment] 2023-02-10 02:46
Hi @JonnyG123789. Thank you, but a minimum working example (MWE) is the code you wrote to make the figure that *uses* the code in this repository. You can assume we have copies of this code, but what we don't have is any knowledge of how you've used it to get this result. Or to put it another way, a MWE is code (using these tools) that I can copy into my Matlab and see the same problem you're seeing.

**Comment by JonnyG123789** [comment] 2023-02-10 03:14
After load yaml,using command to load csv file:
`ans=ingest_vicon_data('vicon.csv');`
Then,plot:
`plot_multiple_trajectories(ans);
`

**Comment by gammell** [comment] 2023-02-11 02:05
Thanks @JonnyG123789 , we'll take a look.

**Comment by gammell** [comment] 2023-02-12 01:03
Hi @JonnyG123789 , Just a quick note that we've replicated the issue and we're working to sort out exactly where the problem is. We'll let you know.

**Comment by JonnyG123789** [comment] 2023-02-12 01:28
Fine. I'm looking forward to your reply.Thank you for your contributions in OMD.






苟荣松-成都理工大学
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "robotic-esp/dataset_tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月12日(星期天) 上午9:03
***@***.***&gt;;
抄送:&nbsp;"Rongsong ***@***.******@***.***&gt;;
主题:&nbsp;Re: [robotic-esp/dataset_tools] plot vicon trajectories (Issue #5)





 
Hi @JonnyG123789 , Just a quick note that we've replicated the issue and we're working to sort out exactly where the problem is. We'll let you know.

**Comment by JonnyG123789** [comment] 2023-02-21 01:42
Hi,Is this problem solved?

**Comment by gammell** [comment] 2023-02-21 20:52
Hi,

The problem is that `ingest_vicon_data` and `plot_multiple_trajectories` expect transform matrices that are the ~~transpose~~ inverse of each other. This problem can be solved _in practice_ by either ~~transposing~~ taking the inverse of the data you read in from the CSV before you put it into a transform matrix OR plotting the ~~transpose~~ inverse of the transform matrix currently read from the CSV.

But only one of those two is the **correct** solution conceptually. So I'm in the process of working out which function should actually have the ~~transpose~~ inverse.

**Comment by JonnyG123789** [comment] 2023-02-22 06:45
OK thanks, after` ingest_vicon_data`,I try to  transpose every 4×4 matrix befor plot, but the results seems incorrect.

**Comment by gammell** [comment] 2023-02-22 13:23
I'm very sorry, I misspoke. I meant inverse not transpose. Changing
https://github.com/robotic-esp/dataset_tools/blob/fee1a304ebb5a7028e6d685ef3ef9c09d4824fd5/ingest_vicon_data.m#L27
to
```matlab
vicon_trajectories{ind}{end+1,1} = invT(reshape(vicon_data{i,11:end}',4,4)');
```
in `ingest_vicon_data` will give you data that can then be plotted directly by `plot_multiple_trajectories`.

I will be updating the repository shortly.

**Edit**: `invT` is the analytical inverse of the 4x4 transform matrix.

**Comment by JonnyG123789** [comment] 2023-02-24 01:15
Thank you for your contribution!the problem has to be solved!!

**Comment by gammell** [comment] 2023-02-25 14:29
Hi @JonnyG123789 can you please check if the code in this branch works for you?
https://github.com/robotic-esp/dataset_tools/tree/fix/jon

**Comment by JonnyG123789** [comment] 2023-02-26 09:37
Yes!&nbsp; It worked now ! Thank you so much!




苟荣松-成都理工大学
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "robotic-esp/dataset_tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月25日(星期六) 晚上10:30
***@***.***&gt;;
抄送:&nbsp;"Rongsong ***@***.******@***.***&gt;;
主题:&nbsp;Re: [robotic-esp/dataset_tools] plot vicon trajectories (Issue #5)





 
Hi @JonnyG123789 can you please check if the code in this branch works for you?
 https://github.com/robotic-esp/dataset_tools/tree/fix/jon

**Comment by gammell** [comment] 2023-04-21 18:09
This has now been merged into the main branch.

**Closed as completed** 2023-04-21 18:08 UTC
Labels: bug
